apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rbac/policy
        value: |
          g, gitops-admins, role:admin
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
    target:
      kind: ArgoCD
  - patch: |-
      - op: add
        path: /users
        value:
          - codekow
    target:
      kind: Group
      name: gitops-admins
  - path: patch-resource-customizations.yaml
    target:
      kind: ArgoCD
