- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-autoscale
        namespace: openshift-gitops
        path: components/configs/autoscale/overlays/workshop-50
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-console
        namespace: openshift-gitops
        path: components/configs/console/overlays/workshop
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-namespaces
        namespace: openshift-gitops
        path: components/configs/namespaces/aggregate/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-rbac
        namespace: openshift-gitops
        path: components/configs/rbac/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-sandbox-cleanup
        namespace: openshift-gitops
        path: components/configs/simple/sandbox-cleanup
