apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: cluster-admins
    path: patch-cluster-admins-group.yaml
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: cluster-readers
    path: patch-cluster-readers-group.yaml
