apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-pgadmin4
  namespace: openshift-gitops
spec:
  destination:
    namespace: pgadmin4
    server: https://kubernetes.default.svc
  project: edge-workshop-tenant
  source:
    path: tenants/edge-workshop/components/configs/simple/pgadmin4
    repoURL: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
    targetRevision: main
  syncPolicy:
    automated: {}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers: []
      jqPathExpressions:
        # - .spec.template.spec.initContainers[] | select(.name == "injected-init-container")
        # - .spec.template.spec.containers[].image
        - .spec.template.spec.containers[] | select(.name == "pgadmin4") | .image
