- op: add
  path: /spec/identityProviders
  value:
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: claim
      name: Internal
      type: HTPasswd
- op: add
  path: /spec/identityProviders/-
  value:
    htpasswd:
      fileData:
        name: htpasswd-workshop-secret
    mappingMethod: claim
    name: Workshop-Users
    type: HTPasswd
- op: add
  path: /spec/identityProviders/-
  value:
    github:
      ca:
        name: ''
      clientID: 49d67e48e7ae82b0e9ce
      clientSecret:
        name: github-secret
      hostname: ''
      teams:
        - Enterprise-Neurosystem/Edge
    mappingMethod: claim
    name: Enterprise-Neurosystem
    type: GitHub
- op: add
  path: /spec/templates
  value:
    # error:
    #   name: login-custom
    login:
      name: login-custom
    # providerSelection:
    #   name: login-custom
