apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edge-anomaly-detection-tenant-applicationset
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: edge-anomaly-detection-namespaces
            path: tenants/edge-anomaly-detection/components/namespaces/overlays/default/
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: edge-anomaly-detection-rbac
            path: tenants/edge-anomaly-detection/components/rbac/overlays/default/
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: edge-anomaly-detection-argocd
            path: tenants/edge-anomaly-detection/components/argocd/overlays/default/
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: edge-anomaly-detection-tenant
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source:
        repoURL: 'https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git'
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
