apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-robotics-edit-rolebinding
  namespace: edge-robotics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: edge-robotics-admin
