apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../../components/argocd/apps/overlays/default
  - ../../../components/argocd/applicationsets/overlays/default
  - ../../../components/argocd/projects/overlays/default

patches:
  - path: patch-applicationset-repo-revision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
  # Uncomment patches to disable automatic sync
  - path: patch-applicationset-manual-sync.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
  - path: patch-application-manual-sync.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
