apiVersion: addons.managed.openshift.io/v1alpha1
kind: Addon
metadata:
  finalizers:
  - addons.managed.openshift.io/cache
  labels:
    hive.openshift.io/managed: "true"
  name: managed-odh
spec:
  commonAnnotations:
    foo: bar
  displayName: Red Hat OpenShift Data Science
  install:
    olmAllNamespaces:
      catalogSourceImage: quay.io/osd-addons/rhods-index@sha256:5285cb10cef89845499d16d3b2b09f3bb65ed4e5fdfee2998c0a27298356b880
      channel: beta
      namespace: redhat-ods-operator
      packageName: rhods-operator
    type: OLMAllNamespaces
  namespaces:
  - name: redhat-ods-operator
  - name: redhat-ods-monitoring
  - name: redhat-ods-applications
  pause: false
  version: 1.22.1-5
