apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: claim
      name: htpasswd_provider
      type: HTPasswd
    - htpasswd:
        fileData:
          name: workshop-htpasswd
      mappingMethod: claim
      name: WorkshopAttendees
      type: HTPasswd
