apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-prediction-failure-view
  namespace: edge-prediction-failure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 'system:authenticated'