apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - edge-anomaly-detection-admins-rolebinding.yaml
  - edge-anomaly-detection-gitops-admins-rolebinding.yaml
  - edge-demo-anomaly-detection-admins-rolebinding.yaml
  - project-admin-group.yaml
