apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  # argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=true

resources:
  - ../../base
  - link-workshop.yaml

patches:
  - target:
      kind: ConsoleNotification
      name: banner-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'Welcome to the `AI/ML Intelligent Applications for the Edge` Workshop'
