apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: autoscaling.openshift.io
      kind: ClusterAutoscaler
    patch: |-
      - op: replace
        path: /spec/resourceLimits/maxNodesTotal
        value: 20
      - op: replace
        path: /spec/resourceLimits/cores
        value:
          min: 4
          max: 310
      - op: replace
        path: /spec/resourceLimits/memory
        value:
          min: 64
          max: 1000
