kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: workshop-attendees
users:
  - user01
  - user02
  - user03
  - user04
  - user05
  - user06
  - user07
  - user08
  - user09
  - user10
  - user11
  - user12
  - user13
  - user14
  - user15
  - user16
  - user17
  - user18
  - user19
  - user20
