apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin4
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/instance: pgadmin4
  name: pgadmin4
  namespace: pgadmin4
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    deployment: pgadmin4
