apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pgadmin4
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/instance: pgadmin4
  name: pgadmin4-pvc
  namespace: pgadmin4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
