apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: strimzi-operator
            path: components/operators/strimzi/operator/overlays/stable
        # RHODS is tricky
        # we'll try this out for now
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: rhods-operator
            path: components/operators/rhods/operator/overlays/stable
        # - cluster: local
        #   url: https://kubernetes.default.svc
        #   values:
        #     name: aap-operator
        #     path: components/operators/ansible-automation-platform/operator/overlays/stable-2.2-cluster-scoped
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        app.kubernetes.io/instance: cluster-config-manager
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
      source:
        repoURL: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      ## ignoring the difference in label
      ignoreDifferences:
      - group: apps
        kind: Namespace
        jsonPointers:
          - /metadata/labels/app.kubernetes.io/instance
      - group: apps
        kind: Subscription
        jsonPointers:
          - /metadata/labels/app.kubernetes.io/instance
