apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: demo-rhods-airflow
  namespace: openshift-gitops
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/demos/instance/airflow
    repoURL: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
