apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
  name: "default"
spec:
  podPriorityThreshold: -10 
  resourceLimits:
    maxNodesTotal: 4
    cores:
      min: 4
      max: 64
    memory:
      min: 64
      max: 256
    gpus:
      - type: nvidia.com/gpu
        min: 0
        max: 1
  scaleDown:
    enabled: true
    delayAfterAdd: 3m
    delayAfterDelete: 30s
    delayAfterFailure: 30s
    unneededTime: 5m
    utilizationThreshold: "0.4"
