apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: ConsoleNotification
      name: banner-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'This cluster is in process of being retired - Contact Audrey Guidera for more info'
