apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAa1DXhEzPT+i4J1h+ygkvbd8s7G2y3X+uQrYXbceNaBpTqhwEACqhSS/VKV4DJScW3IRjjkGcIH26/IFJhouW0JTvFbcHjIaNg6Jssk0G9DtAGQAESnwm3b5gXVu3nQHVaiLJbDm3CRhmA1gCyQpuBjqn9sKBZSjrkuQlKHPVi5cqbEyT4u0LbfL2x5Hju2aUMWiEyLkMFlgp+vjbTm4HK/7w82bJcPgnbpKH9ZXtaRb7JzLX2xge9Jrx6VHW/yXKI3xcWGfzjhUFDJ8YojVWJVHUXNYA/J3ep6WlDW54npbszv2lCSzYb+5HNBoA3HZLA4eUfKpjVS4cuocSz7hXBxRpxNrke26UuthI7FAPcsTZfS4BCP3MAJQvFAcHfRhCH2oGLknWNQW9gQ359coBMcBqSaXJ/IE8nYi5fcL0gxTtziFVhszUqUi7yUzP43gT869uG1v+8jEvG9BUuquyWRu6KRMob/PgpsndHS6Xrxs112NVYpRqeryrv6bNoZP5kPGo4fKHQB7XdLTokvxtapRYKQnhv0teVJS8LRSkyGy/GxMgtq3cczfmR8PBqi5/MshVhYfude02Ha9q6kAfI94FpfQKuH1GERlK8+dlK3DHUL3bfT/GxGD5enEhchQ7+VJtgJBrgem2B/2+7qlHp29gnUPVcfxkOk3vnv7tMxWvP7t9eH8a+bvdyhinjJ57WQMYMm3H3wv53ZWGzHtbcLanhClbL7VdpYc9duqZ4SKtHlJkhQC/d
  template:
    metadata:
      name: github-secret
      namespace: openshift-config
    type: Opaque
