apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBpfJer9ZIJeqSOcpECg9bByG0JhTd3bfgdcSt4kKm87Wa4oxz1QgrPKByI8bZ8lEinCT1aV2zgEif7JoH+S/4XpP88bjdrs6dZsa4MoWy1wFP6ls7h0C7/i+xafz5D5lK5Io42xETFuYmcO4r2T79EkdSRCqu5JcJltAWSZKj2NrJzxlrCn0yF9G39lLYQUxT75AHnbIZT+eZt+epOGrledCkazTe51kG5ObTOQc/u8JdMWpPOUUwDR3xvtNpgNANoSERfiOOW1A9+Ut/5ijcWyTySeffklgIyNUCGoG9ouVVwSKvRJjL6ZZZ+MZ0q64jDFY1QrxN5bQxe2H7D+5k4y8nX6b9XALMuh4UBxxjzdhC+tcPp1IesIrvBLn0Rd4d+/WVZcvWVOMQPvnyH0MoHk6MC++nUH1BCHv61fLnkC9zd1PCQAJq7VVr5JMCDi3qg/lUH3qFXp4bz4DO1Q38ogc4jxTQreGTf+0vzaNLi+RvnJEju3+pRasvbNMVODDR5SIpf9Wo5YP5Vi9hO95KWux9ID0l/4ebMA11eCINjvxQLs+BG7tK/+NiF/uHR+gTsbPOApL8S1yQO5nR4rPsl08xk0qR++EMAuKTS7ZO6B2nw0h/nWf6n6ytkJI4zEmJ/xX0ysAg035f43UhQNHHv7/xdp5XqUxDCUcnw1CnCYwPdb/HarcTOoKTpGSUiuTbzZypSCaZlXRCmkRT+L3z7CvVEETS9w46OMIUbIP4=
  template:
    metadata:
      name: github-secret
      namespace: openshift-config
